//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using ChimeraVirtualAds.Internal;

namespace ChimeraVirtualAds.API
{
	public class AdInstance:IAdInstance
	{
		private String instanceId;
		private GameObject adObject;

		public AdInstance (String instanceId, GameObject adObject)
		{
			this.instanceId = instanceId;
			this.adObject = adObject;
		}
		public String GetInstanceId(){
			return this.instanceId;
		}
		public void DisplayTexture(Texture2D tex){
			adObject.GetComponent<Renderer> ().material.mainTexture = tex;
		}
	}
}

