//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using ChimeraVirtualAds.API;

namespace ChimeraVirtualAds
{
	public static class AdManager
	{
		private static Hashtable imageTextureAds = new Hashtable();
		private static bool isUpdateRequired = true;
		public static void AddImageTextureAd(ImageTextureAd imageTextureAd){
			imageTextureAds.Add (imageTextureAd.GetAdId(), imageTextureAd);
			isUpdateRequired = true;
		}

		public static void AddImageTextureInstance(String adId, AdInstance instance){
			ImageTextureAd ad = (ImageTextureAd)imageTextureAds[adId];
			ad.AddInstance(instance);
		}

		public static void Start(){
		}

		public static ImageTextureAd GetImageTextureAd(String adId){
			return (ImageTextureAd)imageTextureAds [adId];
		}

		public static void Update() {
			if (!isUpdateRequired)
				return;
			isUpdateRequired = false;
			foreach (DictionaryEntry entry in imageTextureAds) {
				ImageTextureAd ad = (ImageTextureAd)entry.Value;
				if(!ad.IsTextureGenerated()){
					ad.GenerateTexture();
					ad.DisplayTexture();
					isUpdateRequired = true;
				}
			}
		}
	}
}

